services:
  rabbitmq:
    build: .
    hostname: rabbitmq-server
    ports:
      - "${RABBIT_UI_PORT}:15672"
      - "${RABBIT_PORT}:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/mnesia
    restart: unless-stopped

volumes:
  rabbitmq_data: